version: "3.9"
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=3
    volumes:
      - .:/app
    ports:
      - "8200:8000"
    env_file:
      - .env
    networks:
      - database-network

networks:
  database-network:
    external: true
