# Generated by Django 5.2.6 on 2025-09-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_case_study_url_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job_list',
            field=models.TextField(blank=True, help_text='List of job responsibilities, one per line'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
