# Generated by Django 5.2.6 on 2025-09-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_job_list_profile_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
