# Generated by Django 5.2.6 on 2025-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
