# Generated by Django 5.2.6 on 2025-09-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_skill_proficiency_alter_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thesis_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='thesis_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
