# Generated by Django 5.2.6 on 2025-10-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_education_thesis_name_education_thesis_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, help_text='Required for work projects', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('work', 'Work Project'), ('self', 'Personal Project')], default='self', max_length=10),
        ),
    ]
